# --------------------------------------------------------------------
# Copyright (c) 2007 MediaTek Inc.
#
# All rights reserved. Copying, compilation, modification, distribution
# or any other use whatsoever of this material is strictly prohibited
# except in accordance with a Software License Agreement with
# MediaTek Inc.
# --------------------------------------------------------------------

# --------------------------------------------------------------------
# This file is used for identifying version of GCC for Linux Kernel Source 2.6
# --------------------------------------------------------------------

obj-m := .kversion.o
