/*
 * Generated by MTK Drv_CodeGen Version 04.08.0 for MT6575_NP. Copyright MediaTek Inc. (C) 2011.
 * Thu Nov 22 14:40:36 2012
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


